name: tests
on: [push]
jobs:
  unit:
    name: IO tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install column command
        run: sudo apt-get install bsdmainutils

      - name: Verbose test output
        run: ./test/iotest -v

      - name: Run tests
        run: ./test/iotest

  static-control:
    name: Shell static check
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run Shellcheck
        uses: azohra/shell-linter@latest
        with:
          path: "src/tradelog.sh"