name: unit-tests
on: [push]
jobs:
  unit:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
      - uses: actions/checkout@v2

      - name: Setup PHP, extensions and composer with shivammathur/setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: mbstring
        env:
          update: true

      - name: Check PHP Version
        run: php -v

      - name: Run tests
        run: php test.php

  static-control:
    name: Shell static controll
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
      - uses: actions/checkout@v2

      - name: Run Shellcheck
        uses: azohra/shell-linter@latest
        with:
          path: "src/tradelog.sh"